AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  DynamoDBReadUnits:
    Default: 5
    Description: Number of DynamoDB read units to provision for each table
    MaxValue: 10000
    MinValue: 1
    Type: Number
  DynamoDBWriteUnits:
    Default: 5
    Description: Number of DynamoDB write units to provision for each table
    MaxValue: 10000
    MinValue: 1
    Type: Number
  LicenseEmail:
    AllowedPattern: '^[a-zA-z\d]+(\.[a-zA-Z\d]+)*@[a-zA-Z\d](\.[a-zA-Z\d]+)+$'
    Description: E-mail address to return with the server license status
    Type: String

Globals:
  Function:
    CodeUri: bin/
    Environment:
      Variables:
        DYNAMODB_USERS_TABLE: !Ref UsersTable
        LICENSE_EMAIL: !Ref LicenseEmail
    Runtime: python3.6
    Timeout: 20

Resources:

  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: username
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBReadUnits
        WriteCapacityUnits: !Ref DynamoDBWriteUnits
      TableName: !Sub MousikeUsers-${AWS::Region}

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /rest/ping
            Method: get
      Handler: ping.lambda_handler

  GetLicenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /rest/getLicense
            Method: get
      Handler: get_license.lambda_handler
